name = "swiftui_vm_lab"
description = "Multi-threaded View-Model paradigm of Apple's SwiftUI Windowing system"
version = "0.1.0"

authors = ["William J. FRANCK"]
maintainers = ["William J. FRANCK <william@sterna.io>"]
maintainers-logins = ["captain-haddock17"]

executables = ["swiftui_vm_lab"]
